jobs:
  ethusd:
    runs-on: ubuntu-latest
    outputs:
      - price: ${{ steps.ethusd.outputs.price }}
    steps:
      - name: Get ETH/USD Price Feed
        uses: web3actions/price-feeds@9f8940cd7765840b000e934fdd89e46f6c15f717
        id: ethusd
        with:
          rpc-node: ${{ secrets.RPC_NODE }}