name: Crypto Actions Token Airdrop
on:
  issues:
    types: [ opened ]

jobs:
  airdrop:
    name: Crypto Actions Token Airdrop
    runs-on: ubuntu-latest
    if: fromJSON(github.event.issue.body).requestId
    steps:
      - uses: actions/checkout@v2

      - name: Count Pull Requests
        id: count-pull-request
        uses: actions/github-script@v4
        with:
          script: await require('./.github/workflows/count-pull-requests')({ github, context, core })
      
      - name: Read Workflow Request
        id: request
        uses: cryptoactions/tx@main
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          contract: "0xD05B06F1F0456605779b41b4a1FbB21d7647f7CB"
          function: getGithubWorkflowRequest(uint256) returns(string hash,address account,uint256 fee,address sender,string name,string githubUserId,bool fulfilled)
          inputs: '[${{ fromJSON(github.event.issue.body).requestId }}]'

      - run: echo "${{ toJSON(github.event.issue) }}"

      - name: Send Airdrop
        if: |
          fromJSON(steps.request.outputs.result)[6] == false &&
          fromJSON(steps.request.outputs.result)[5] == github.event.issue.author.node_id
        uses: cryptoactions/tx@main
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: "0xD05B06F1F0456605779b41b4a1FbB21d7647f7CB"
          function: fulfillAirdrop(uint256,uint256)
          inputs: '[${{ fromJSON(github.event.issue.body).requestId }}, ${{ steps.count-pull-request.outputs.count }}]'