name: Crypto Actions Token Airdrop
on:
  issues:
    types: [ opened ]

jobs:
  airdrop:
    name: Crypto Actions Token Airdrop
    runs-on: ubuntu-latest
    if: fromJSON(github.event.issue.body).requestId
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci

      - name: Count Contributions
        id: contributions
        uses: actions/github-script@v4
        with:
          script: |
            const count = require('./.github/workflows/count-contributions')
            await count(context, core, "${{ secrets.GITHUB_TOKEN }}")
      
      - name: Read Workflow Request
        id: request
        uses: cryptoactions/tx@main
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          contract: "0xe0E0a65B81a5B778Be82C444640AeC334dA8DcC9"
          function: getGithubWorkflowRequest(uint256) returns(string,address,uint256,address,string,string,bool)
          inputs: '[${{ toJSON(fromJSON(github.event.issue.body).requestId) }}]'

      - name: Send Airdrop
        id: airdrop
        if: |
          fromJSON(steps.request.outputs.result)[6] == false &&
          fromJSON(steps.request.outputs.result)[5] == github.event.issue.user.node_id
        uses: cryptoactions/tx@main
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: "0xe0E0a65B81a5B778Be82C444640AeC334dA8DcC9"
          function: fulfillAirdrop(uint256,address,uint256)
          inputs: '[${{ toJSON(fromJSON(github.event.issue.body).requestId) }}, "${{ fromJSON(github.event.issue.body).address }}", ${{ steps.contributions.outputs.count }}]'
      
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        env:
          RESULT_BODY: "Sent ${{ steps.contributions.outputs.tokens }} ACTION to ${{ fromJSON(github.event.issue.body).address }}\nTransaction Hash: ${{ fromJSON(steps.airdrop.outputs.result).transactionHash }}"
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.RESULT_BODY }}