name: Web3 Actions Token Airdrop
on:
  issues:
    types: [ opened ]

jobs:
  airdrop:
    name: Web3 Actions Token Airdrop
    runs-on: ubuntu-latest
    if: fromJSON(github.event.issue.body).requestId
    steps:
      - name: Add processing comment
        id: comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Processing...

      - uses: actions/checkout@v2
        with:
          ref: "a36803eb19f7ffda60659ca06d97fd784d898678"
      - uses: actions/setup-node@v2
      - run: npm ci

      - name: Count Contributions
        id: contributions
        uses: actions/github-script@v4
        with:
          script: |
            const count = require('./.github/workflows/count-contributions')
            await count(context, core, "${{ secrets.GITHUB_TOKEN }}")
      
      - name: Check Payment
        id: payment
        uses: web3actions/tx@main
        with:
          network: kovan
          infura-key: ${{ secrets.INFURA_KEY }}
          contract: "0xe0E0a65B81a5B778Be82C444640AeC334dA8DcC9"
          function: isPayed(string) returns(bool)
          inputs: '["${{ github.event.issue.user.node_id }}"]'

      - name: Send Airdrop
        id: airdrop
        if: |
          fromJSON(steps.payment.outputs.result)[0] == true
        uses: web3actions/tx@main
        with:
          network: kovan
          infura-key: ${{ secrets.INFURA_KEY }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: "0xe0E0a65B81a5B778Be82C444640AeC334dA8DcC9"
          function: fulfillAirdrop(uint256,address,uint256,uint256,bytes) # ...,uint256,bytes for run id and signature
          inputs: '["${{ github.event.issue.user.node_id }}", "${{ fromJSON(github.event.issue.body).address }}", ${{ steps.contributions.outputs.count }}]'
      
      - name: Add success comment
        if: fromJSON(steps.payment.outputs.result)[0] == true
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          reactions: 'rocket'
          edit-mode: replace
          body: |
            Sent ${{ steps.contributions.outputs.tokens }} ACTION to ${{ fromJSON(github.event.issue.body).address }}
            Transaction Hash: ${{ fromJSON(steps.airdrop.outputs.result).transactionHash }}

      - name: Add failure comment
        if: fromJSON(steps.payment.outputs.result)[0] == false
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          reactions: 'confused'
          edit-mode: replace
          body: Airdrop already claimed or oracle fee not payed for @${{ github.event.issue.user.login }}.