name: Crypto Actions Token Airdrop
on:
  issues:
    types: [ opened ]

jobs:
  airdrop:
    name: Crypto Actions Token Airdrop
    runs-on: ubuntu-latest
    if: fromJSON(github.event.issue.body).requestId
    steps:
      - uses: actions/checkout@v2

      - name: Count Pull Requests
        id: count-pull-request
        uses: actions/github-script@v4
        with:
          script: await require('./.github/workflows/count-pull-requests')({ github, context, core })
      
      - name: Read Workflow Request
        id: request
        uses: cryptoactions/tx@main
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          contract: "0x8856E7590442cB4610022b813C9ca873f2e185e0"
          function: getGithubWorkflowRequest(uint256)
          inputs: '[${{ fromJSON(github.event.issue.body).requestId }}]'

      - name: Send Airdrop
        if: ${{ fromJSON(steps.request.outputs.result).fulfilled == 'false' }}
        uses: cryptoactions/tx@main
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          to: "0x8856E7590442cB4610022b813C9ca873f2e185e0"
          function: fulfillAirdrop(uint256,uint256,address)
          inputs: '[1, ${{ steps.count-pull-request.outputs.count }}]'