name: Crypto Actions Token Airdrop
on:
  issues:
    types: [ opened ]

jobs:
  airdrop:
    name: Crypto Actions Token Airdrop
    runs-on: ubuntu-latest
    if: fromJSON(github.event.issue.body).requestId
    steps:
      - uses: actions/checkout@v2

      - name: Count Pull Requests
        id: count-pull-request
        uses: actions/github-script@v4
        with:
          script: await require('./.github/workflows/count-pull-requests')({ github, context, core })
      
      - name: Read Workflow Request
        id: request
        uses: cryptoactions/tx@0a51a4099a6d9d011a7a710a9d63d2fa00fb2f04
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          contract: "0x8856E7590442cB4610022b813C9ca873f2e185e0"
          function: getGithubWorkflowRequest
          input-types: uint256
          input-values: '[${{ fromJSON(github.event.issue.body).requestId }}]'

      - name: Send Airdrop
        if: |
          fromJSON(steps.request.outputs.result).fulfilled == 'false' &&
          fromJSON(steps.request.outputs.result).githubUserId == github.event.issue.author.node_id
        uses: cryptoactions/tx@0a51a4099a6d9d011a7a710a9d63d2fa00fb2f04
        with:
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract: "0x8856E7590442cB4610022b813C9ca873f2e185e0"
          function: fulfillAirdrop
          inpu-types: uint256,uint256
          input-values: '[${{ fromJSON(github.event.issue.body).requestId }}, ${{ steps.count-pull-request.outputs.count }}]'